general:
  OS: windows
  path_to_binaries: C:\Users\threedom\Desktop\OpenMVG\ReleaseV1.6.Halibut.WindowsBinaries_VS2017\ReleaseV1.6.Halibut.WindowsBinaries_VS2017
  openmvg_database: C:\Users\threedom\Desktop\OpenMVG\ReleaseV1.6.Halibut.WindowsBinaries_VS2017\ReleaseV1.6.Halibut.WindowsBinaries_VS2017\sensor_width_database\sensor_width_camera_database.txt